topics:
  gsupport:
    name: General Support
    description: "General support regarding Infinity List"
    emoji: 🤖
    questions:
      - question: "Anything else we need to know?"
        placeholder: "I have..."
        required: false
    ping:
      - "805761849601294336"
  reviewhelp:
    name: Bot Reviews
    description: "Questions regarding a review on your bot"
    emoji: 📝
    questions:
      - question: "What is the bot ID in question?"
        placeholder: "1234567890"
        required: true
      - question: "Who reviewed your bot?"
        placeholder: "Bob"
        required: false
      - question: "Anything else we need to know?"
        placeholder: "I have..."
        required: false
    ping:
      - "805761849601294336"
  uhelp:
    name: Urgent Help
    description: "Urgent help regarding Infinity List"
    emoji: 🚨
    questions:
      - question: "Why do you feel this is urgent?"
        placeholder: "There is a raid going on/hacked account..."
        required: true
      - question: "Anything else we need to know?"
        placeholder: "I have..."
        required: false
    ping:
      - "805761849601294336"
      - "911918122359988244"
  request:
     name: Feature Request
     description: "Request new features to help improve Infinity List!"
     emoji: 👥
     ping:
      - "815854927719956490"
      - "869527375925370891"
  giveaway:
     name: Claim Giveaway
     description: "Did you win a giveaway? Claim your Prize!"
     emoji: 💵
     questions:
        - question: "Client ID / Bot ID"
          placeholder: "What bot would you like this prize issued to?"
          required: false
     ping:
      - "911918122359988244"
      - "1223897744784228372"
database:
  postgres: postgresql:///infinity
  redis: redis://localhost:6379
  file_storage_path: /silverpelt/cdn/ibl/blobs/tickets
  exposed_path: https://reedwhisker.infinitybots.gg/ticket/
channels:
  thread_channel: 816156732929081366
  log_channel: 815511720121335838
